--- 
title: "NYC Job Analysis"
author: "Yunxiao Wang, Shangzhi Liu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

This project is created by Yunxiao Wang and Shangzhi Liu in Final Project Group 39. 

As graduate students, besides finishing our studies, finding a suitable job is also one of the most important things for us. Especially in New York, a bustling international city, there are opportunities everywhere. Many companies have openings and are eager to hire competent people. 

However, although there are many job postings, it is always a problem for job seekers to find the most suitable job for them from all the information of these job postings. Therefore, our group choose the topic of job postings in New York City to help people better choose the jobs that suit them by summarizing the useful information and trend from these job postings, such as salary, categories, and skills. What's more, we also focus on some questions that graduate students also care about when they look for jobs, for example, what skills or requirements are needed to get a high salary job? What kind of job position is needed most in NYC? For people with fixed salary range expectation, what kind of jobs suit him and are in high demand?

However, although there are many job postings, it is always a problem for job seekers to find what kind of jobs are suitable for them from all the information of these job postings, especially for those who feel confused and don't have a specific direction of employment. Therefore, our group choose the topic of job postings in New York City to help people better choose the jobs that suit them and determine their work direction by summarizing the useful information and trend from these job postings, such as salary, categories, requirements, and skills. What's more, we also focus on some questions that people also care about when they look for jobs, for example, what kind of job category or requirements are needed to get a high salary? What kind of job position is needed most in NYC? For people who have no direction but have specific requirements for the future salary range, what kind of jobs suit them and what requirements or skills should they need to possess in order to get this kind of jobs?

